allow_tearing=2
blur=0
blur_layer=0
shadows=1
layer_shadows=0
shadow_only_floating=1
shadows_size=12
shadows_blur=18
shadows_position_x=0
shadows_position_y=0
shadowscolor=0x000000d9
animations=1
layer_animations=1
animation_type_open=slide
animation_type_close=slide
layer_animation_type_open=fade
layer_animation_type_close=fade
animation_fade_in=1
animation_fade_out=1
fadein_begin_opacity=0.72
fadeout_begin_opacity=0.90
animation_duration_move=180
animation_duration_open=180
animation_duration_tag=180
animation_duration_close=180
animation_duration_focus=80
animation_curve_open=0.22,1.0,0.36,1.0
animation_curve_move=0.22,1.0,0.36,1.0
animation_curve_tag=0.22,1.0,0.36,1.0
animation_curve_close=0.22,1.0,0.36,1.0
animation_curve_focus=0.22,1.0,0.36,1.0
animation_curve_opafadein=0.22,1.0,0.36,1.0
animation_curve_opafadeout=0.40,0.00,1.0,1.0
tag_animation_direction=1
focused_opacity=1.0
unfocused_opacity=1.0
border_radius=6
borderpx=2
no_border_when_single=0
no_radius_when_single=0
smartgaps=0
gappih=8
gappiv=8
gappoh=8
gappov=8
rootcolor=0x0A0C10ff
bordercolor=0x333333ff
dropcolor=0x5080bf55
focuscolor=0x5080bfff
maximizescreencolor=0x5080bfff
urgentcolor=0xff5555ff
scratchpadcolor=0x888888ff
globalcolor=0x555555ff
overlaycolor=0xddddddff
