keymode=common
bind=SUPER+SHIFT,r,reload_config

keymode=default
bind=SUPER,Return,spawn,kitty
bind=SUPER,e,spawn,nautilus
bind=SUPER,d,spawn,/home/rel/.config/rofi/launch.sh launcher
bind=SUPER,p,spawn,/home/rel/.config/rofi/launch.sh powermenu
bind=SUPER,w,spawn,/home/rel/.config/mango/scripts/wallpaper.sh --select
bind=SUPER,q,killclient
bind=SUPER+SHIFT,s,spawn,/home/rel/.local/bin/dot-screenshot.sh --selection
bind=SUPER+SHIFT,m,quit
bind=ALT,Tab,focusstack,next
bind=ALT+SHIFT,Tab,focusstack,prev
bind=SUPER,left,focusdir,left
bind=SUPER,right,focusdir,right
bind=SUPER,up,focusdir,up
bind=SUPER,down,focusdir,down
bind=SUPER,f,togglemaximizescreen
bind=SUPER+SHIFT,f,togglefullscreen
bind=SUPER,c,centerwin
bind=SUPER,i,minimized
bind=SUPER+SHIFT,i,restore_minimized
bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client
bind=SUPER+CTRL,left,smartmovewin,left
bind=SUPER+CTRL,right,smartmovewin,right
bind=SUPER+CTRL,up,smartmovewin,up
bind=SUPER+CTRL,down,smartmovewin,down
bind=SUPER+ALT,left,smartresizewin,left
bind=SUPER+ALT,right,smartresizewin,right
bind=SUPER+ALT,up,smartresizewin,up
bind=SUPER+ALT,down,smartresizewin,down
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize
