keymode=common
bind=SUPER+SHIFT,r,reload_config

keymode=default
bind=SUPER,Return,spawn,kitty
bind=SUPER,e,spawn,nautilus
bind=SUPER,d,spawn,noctalia msg panel-toggle launcher
bind=SUPER,p,spawn,noctalia msg panel-toggle session
bind=SUPER,w,spawn,noctalia msg panel-toggle wallpaper
bind=SUPER,q,killclient
bind=SUPER,s,spawn,noctalia msg screenshot-fullscreen
bind=SUPER+SHIFT,s,spawn,noctalia msg screenshot-region
bind=SUPER,l,spawn,noctalia msg session lock
bind=SUPER,space,spawn,noctalia msg panel-toggle launcher
bind=SUPER,comma,spawn,noctalia msg settings-toggle
bind=SUPER+SHIFT,m,quit
bind=ALT,Tab,focusstack,next
bind=ALT+SHIFT,Tab,focusstack,prev
bind=SUPER,left,focusdir,left
bind=SUPER,right,focusdir,right
bind=SUPER,up,focusdir,up
bind=SUPER,down,focusdir,down
bind=SUPER,f,togglemaximizescreen
bind=SUPER+SHIFT,f,togglefullscreen
bind=SUPER,c,centerwin
bind=SUPER,i,minimized
bind=SUPER+SHIFT,i,restore_minimized
bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client
bind=SUPER+CTRL,left,smartmovewin,left
bind=SUPER+CTRL,right,smartmovewin,right
bind=SUPER+CTRL,up,smartmovewin,up
bind=SUPER+CTRL,down,smartmovewin,down
bind=SUPER+ALT,left,smartresizewin,left
bind=SUPER+ALT,right,smartresizewin,right
bind=SUPER+ALT,up,smartresizewin,up
bind=SUPER+ALT,down,smartresizewin,down
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

# media and hardware keys
bind=NONE,XF86AudioRaiseVolume,spawn,noctalia msg volume-up
bind=NONE,XF86AudioLowerVolume,spawn,noctalia msg volume-down
bind=NONE,XF86AudioMute,spawn,noctalia msg volume-mute
bind=SHIFT,XF86AudioMute,spawn,pactl set-source-mute @DEFAULT_SOURCE@ toggle
bind=NONE,XF86MonBrightnessUp,spawn,noctalia msg brightness-up
bind=NONE,XF86MonBrightnessDown,spawn,noctalia msg brightness-down
bind=NONE,XF86AudioNext,spawn,noctalia msg media next
bind=NONE,XF86AudioPrev,spawn,noctalia msg media previous
bind=NONE,XF86AudioPlay,spawn,noctalia msg media toggle
bind=NONE,XF86AudioPause,spawn,noctalia msg media toggle
