source=~/.config/mango/env.conf
source=~/.config/mango/appearance.conf
source=~/.config/mango/input.conf
source=~/.config/mango/rules.conf
source=~/.config/mango/binds.conf

exec=/home/rel/.config/mango/scripts/startup.sh
