source=~/.config/mango/env.conf
source=~/.config/mango/appearance.conf
source=~/.config/mango/input.conf
source=~/.config/mango/rules.conf
source=~/.config/mango/binds.conf

exec-once=wl-clip-persist --clipboard regular --reconnect-tries 0 &
exec-once=wl-paste --type text --watch cliphist store &
exec-once=wl-paste --type text --watch xclip -selection clipboard

exec=/home/rel/.config/mango/scripts/startup.sh
