repeat_rate=30
repeat_delay=300
xkb_rules_layout=us
mouse_accel_profile=1
mouse_accel_speed=0
trackpad_accel_profile=1
trackpad_accel_speed=-0.15
tap_to_click=1
tap_and_drag=1
drag_lock=1
trackpad_natural_scrolling=0
disable_while_typing=1
mouse_natural_scrolling=0
sloppyfocus=0
warpcursor=0
focus_on_activate=1
focus_cross_monitor=0
focus_cross_tag=0
enable_floating_snap=1
snap_distance=30
drag_tile_to_tile=0
drag_tile_small=0
