tagrule=id:1,no_hide:1,open_as_floating:1,layout_name:tile
tagrule=id:2,no_hide:1,open_as_floating:1,layout_name:tile
tagrule=id:3,no_hide:1,open_as_floating:1,layout_name:tile
tagrule=id:4,no_hide:1,open_as_floating:1,layout_name:tile
tagrule=id:5,no_hide:1,open_as_floating:1,layout_name:tile
tagrule=id:6,open_as_floating:1,layout_name:tile
tagrule=id:7,open_as_floating:1,layout_name:tile
tagrule=id:8,open_as_floating:1,layout_name:tile
tagrule=id:9,open_as_floating:1,layout_name:tile

windowrule=isfloating:1,width:0.70,height:0.75,title:^(Open File|Save File|Save As|Select File|Choose File|File Upload)$
windowrule=isfloating:1,appid:^(xdg-desktop-portal-gtk|xdg-desktop-portal-kde|org.kde.polkit-kde-authentication-agent-1|polkit-gnome-authentication-agent-1|lxqt-policykit-agent)$

windowrule=isfloating:0,isfullscreen:1,force_tearing:1,appid:^steam_app_.*
windowrule=isfloating:0,isfullscreen:1,force_tearing:1,appid:^osu!\\.exe$
windowrule=isfloating:0,isfullscreen:1,force_tearing:1,title:^osu!$
windowrule=isfloating:0,isfullscreen:1,force_tearing:1,title:.*\\.exe.*
windowrule=isfloating:0,isfullscreen:1,force_tearing:1,title:^Counter-Strike 2$

layerrule=noanim:1,noblur:1,noshadow:1,layer_name:rofi
