source = ~/.config/hypr/hyprlock-backgrounds.conf

window.active.border.color: #5E81AC
window.inactive.border.color: #3B4252
border.width: 2

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = rgba(cdd6f4ff)
    font_size = 80
    font_family = CommitMono Nerd Font Mono
    position = 0, 160
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%A, %d de %B')"
    color = rgba(cdd6f4cc)
    font_size = 22
    font_family = CommitMono Nerd Font Mono
    position = 0, 80
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 55
    rounding = 8
    outline_thickness = 2
    outer_color = rgba(94, 129, 172, 1.0)
    inner_color = rgba(30, 30, 46, 0.8)
    font_color = rgba(230, 230, 230, 1.0)
    placeholder_text = <i>password...</i>
    fail_text = <i>invalid password!</i>
    check_color = rgba(89b4faff)
    fail_color = rgba(f38ba8ff)
    fade_on_empty = false
    position = 0, -40
    halign = center
    valign = center
}
