[spotify]
storage.size=2048
download_attempts = 3
extra_arguments = [
	"--enable-features=UseOzonePlatform", 
	"--ozone-platform=wayland",
	"--disable-gpu-shader-disk-cache",
	"--disable-background-networking",
	"--disable-component-update",
	"--disable-breakpad",
	"--no-pings",
	"--enable-gpu-rasterization"
]
